import { Inter } from 'next/font/google'
import  NavbarSetting  from './NavbarSetting'
import './globals.css'
import { Footer } from './Components/Footer/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {




  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarSetting/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
